// Data model for world effect cards (structures, hazards, weather) with optional health, damage, revenue, vision, and movement modifiers.
using UnityEngine;

[CreateAssetMenu(fileName = "WorldEffectCard", menuName = "Cards/World Effect")]
public class WorldEffectCardData : CardData
{
    [Header("World Effect")]
    // Sprite used when this world effect is manifested on the board.
    public Sprite manifestedSprite;

    // Classifies effect families like buildings, fields, hazards, weather.
    public WorldEffectCategory category;

    // Optional structure/fixture HP. Keep None for effects without health.
    public OptionalInt structureHp;

    // Optional passive or triggered damage generated by this world effect.
    public OptionalInt structureDamage;

    // Optional income generated per turn.
    public OptionalInt revenuePerTurn;

    // Optional visibility modifier (negative for fog, positive for reveal).
    public OptionalInt visionModifier;

    // Optional movement modifier applied to units on affected tiles.
    public OptionalInt movementModifier;

    // Optional duration in turns. Use 0 for permanent/persistent effects.
    public int durationTurns;

    public OptionalInt worldEffectMovementCapacity;

    public override OptionalInt MovementCapacity => worldEffectMovementCapacity;
}